### ISSUE TITLE
How do you actually use this?

### ISSUE THREAD

**Issue by romtim** [tschnz/Realtime-Video-Magnification#3]
Hi, there are no installation and usage instructions, just dependencies.
I installed both QT and opencv. I have no idea how to connect them both together, and what file to use from your project in which of the above mentioned programs.

Please provide a little more information, so that someone who is not so proficient in these programs can launch your program. Thank you!

**Comment by tschnz** [comment]
Hey, the .pro file is the project file for Qt Creator in the source. This was a research project for my bachelors degree. I don't have the time to further develop the project and cross compile it for every platform plus keeping it up to date, so having some knowledge would be quite useful to get it to work.

Depending on which platform you're trying to compile it, make sure you correctly installed OpenCV and QT. Since I only work on Linux I can't provide any help for OSX or Windows. Start Qt Creator open the .pro file in the src folder and try to run the project.

**Comment by tschnz** [comment]
Just loaded the project with Qt Creator 4.2.1, compiled with Qt 5.8 (qmake 3.0) and it worked like a charm. Merged the project with changes that allow compilation on Windows and VS15.

**Comment by romtim** [comment]
Thanks for your reply. 
Yeah, I use Windows. At least I know now which file to use. Its throwing me a opencv development package not found, which I've installed, so I guess I need to provide a link to it somewhere in the project/within Qt. I'll keep googling about that.

Basically, once I link it with opencv, I should just click run and the program will run?
What confused me, is that you mentioned something about compiling first, so do I need to find a way to compile it with qmake 3.0 before I can run it? Or is that another process, to be able to run the program without launching qt?

Thanks!

**Comment by haz** [comment]
Also trying to get this going on windows. @romtim If you install qt creator, you can open the .pro file and start to compile things. I was able to modify it to resolve the include warnings (by pointing it to the right location for opencv), but I believe the linking phase is busted because the .dll files aren't found properly.

@tschnz Is there any qt creator setup you need to do separately, or is it just the .pro file that needs to be done right?

**Comment by tschnz** [comment]
Make sure you installed OpenCV according to the [instructions](https://wiki.qt.io/How_to_setup_Qt_and_openCV_on_Windows). When using CMake, make sure you ticked the WITH_QT option. Also you have to change the .pro file to point to your OpenCV path, to include the DLLs.

You can use this issue to discuss but I will mark it as solved within the next few days, since this is a general "OpenCV+QT on Windows" question, nothing specific to my code. Good luck.

**Comment by haz** [comment]
Thanks @tschnz. Can you confirm that you've gotten it working on Windows? I'll have another go at it tomorrow night, and hopefully find something in the set of instructions that I've passed over in my previous attempts...

**Comment by tschnz** [comment]
I have no machine with Windows, so I currently can't test it. However people did contribute to the repository who used it on Windows10 (with Visual Studio).
